configured_endpoints: 41
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/omnistack-inc-dash%2Fomnistack-ece8f95757741e6626b8fe74adec9865955bb612fd26886b4d48832f667e25f9.yml
