configured_endpoints: 88
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/omnistack-inc-dash%2Fomnistack-9e97617287f323ffd39e0a6126767a5dfa3a31101657a42667908d4c437b8dee.yml
