configured_endpoints: 2
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/omnistack-inc-dash%2Fomnistack-a127ad1d97cb9d4cca6e6294df224217dc6f71bcfd6b15c56961fefc627d10b4.yml
